version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: tunisia-stay-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: tunisia_stay
      MYSQL_USER: tunisia_user
      MYSQL_PASSWORD: tunisia_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - tunisia-stay-network
    restart: unless-stopped

  backend:
    build: .
    container_name: tunisia-stay-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/tunisia_stay?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: tunisia_user
      SPRING_DATASOURCE_PASSWORD: tunisia_pass
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - tunisia-stay-network

    volumes:
      - ./uploads:/app/uploads

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: tunisia-stay-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: password
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - tunisia-stay-network

volumes:
  mysql_data:

networks:
  tunisia-stay-network:
    driver: bridge
